<?php
/**
 * NIELIT BHUBANESWAR - ADMISSION FORM GENERATOR
 * Version: 13.0
 * Fixes: Hollow-Style Watermark, Improved MultiCell Logic, Dynamic Height Handling
 */

session_start();
require_once __DIR__ . '/../config/config.php';

// --- 1. AUTHENTICATION & DATA FETCHING ---
if (!isset($_SESSION['admin'])) { 
    header("Location: login_new.php"); 
    exit(); 
}
if (!isset($_GET['id'])) { 
    header("Location: students.php"); 
    exit(); 
}

$student_id = $_GET['id'];

// Fetch Main Student Data
$sql = "SELECT * FROM students WHERE student_id = ?";
$stmt = $conn->prepare($sql);
$stmt->bind_param("s", $student_id);
$stmt->execute();
$student = $stmt->get_result()->fetch_assoc();

if (!$student) {
    $_SESSION['message'] = "Student record not found.";
    header("Location: students.php");
    exit();
}

// Fetch Education Records
$sql_edu = "SELECT * FROM education_details WHERE student_id = ? ORDER BY id ASC";
$stmt_edu = $conn->prepare($sql_edu);
$education_records = [];
if ($stmt_edu) {
    $stmt_edu->bind_param("s", $student_id);
    $stmt_edu->execute();
    $res_edu = $stmt_edu->get_result();
    while ($row = $res_edu->fetch_assoc()) { 
        $education_records[] = $row; 
    }
    $stmt_edu->close();
}

// --- 2. PDF CLASS DEFINITION (BORDERS & WATERMARK) ---
require_once __DIR__ . '/../libraries/tcpdf/tcpdf.php';

class NIELIT_PDF extends TCPDF {
    public function Header() {
        // Professional Page Border
        $this->SetDrawColor(100, 100, 100);
        $this->SetLineWidth(0.6);
        $this->Rect(10, 10, 190, 275, 'D');

        // --- ULTRA-LIGHT WATERMARK ---
        $this->SetFont('helvetica', 'B', 50);
        
        // Lightened from 200 to 235 (Closer to white)
        $this->SetDrawColor(235, 235, 235); 
        
        // Reduced opacity from 0.35 to 0.18 for a "ghost" effect
        $this->SetAlpha(0.18); 

        $this->StartTransform();
        $this->Rotate(45, 105, 148);
        $this->setTextRenderingMode(1, true, false); // Outline only
        $this->Text(20, 150, 'NIELIT BHUBANESWAR');
        $this->setTextRenderingMode(0, true, false); // Reset to Fill
        $this->StopTransform(); 
        
        // Reset everything for the main content
        $this->SetAlpha(1); 
        $this->SetDrawColor(0, 0, 0); 
    }   

    public function Footer() {
        $this->SetY(-10); 
        $this->SetFont('helvetica', 'I', 9);
        $this->SetTextColor(120, 120, 120);
        $this->Cell(0, 10, 'Generated by NIELIT Management System | Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, 0, 'C');
    }
}

// --- 3. INITIALIZE DOCUMENT ---
$pdf = new NIELIT_PDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetMargins(15, 20, 15);
$pdf->SetAutoPageBreak(TRUE, 25);
$pdf->AddPage();

// --- 4. BRANDING HEADER (CENTERED) ---
$logo_path = __DIR__ . '/../assets/images/bhubaneswar_logo.png';
if (file_exists($logo_path)) { 
    $pdf->Image($logo_path, 15, 15, 26, 0, 'PNG'); 
}

$pdf->SetY(15);
$pdf->SetFont('freesans', 'B', 12); 
$pdf->Cell(0, 7, 'राष्ट्रीय इलेक्ट्रॉनिकी एवं सूचना प्रौद्योगिकी संस्थान ,भुवनेश्वर', 0, 1, 'C');
$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(0, 6, 'National Institute of Electronics & Information Technology, Bhubaneswar', 0, 1, 'C');
$pdf->Cell(0, 5, 'Balasore Extension Center', 0, 1, 'C');

$pdf->SetY(35);
$pdf->SetFont('helvetica', 'B', 16); 
$pdf->SetTextColor(33, 150, 243);
$pdf->Cell(0, 12, 'ADMISSION APPLICATION FORM', 0, 1, 'C');
$pdf->SetTextColor(0, 0, 0);

$pdf->Ln(2);
$pdf->SetDrawColor(180, 180, 180);
$pdf->Line(15, $pdf->GetY(), 195, $pdf->GetY());
$pdf->Ln(6);

// --- 5. MEDIA ZONE (PHOTO & SIGNATURE) ---
$photo_x = 158; 
$start_y = $pdf->GetY();

$photo_path = !empty($student['passport_photo']) ? __DIR__ . '/../' . $student['passport_photo'] : '';
if (!empty($photo_path) && file_exists($photo_path)) {
    $pdf->Image($photo_path, $photo_x, $start_y, 37, 48, '', '', '', true, 300);
} else {
    $pdf->Rect($photo_x, $start_y, 37, 48, 'D');
}

$sig_y = $start_y + 54; 
$pdf->Rect($photo_x, $sig_y, 37, 18, 'D');
$sig_path = !empty($student['signature']) ? __DIR__ . '/../' . $student['signature'] : '';
if (!empty($sig_path) && file_exists($sig_path)) {
    $pdf->Image($sig_path, $photo_x + 1, $sig_y + 1, 35, 16, '', '', '', true, 300);
}
$pdf->SetXY($photo_x, $sig_y + 18);
$pdf->SetFont('helvetica', 'B', 8);
$pdf->Cell(37, 6, 'CANDIDATE SIGNATURE', 0, 0, 'C');

// --- 6. DATA TABLES ---
$pdf->SetY($start_y);
$left_col_w = 140; 

// Section 1: Enrollment
$pdf->SetFont('helvetica', 'B', 11); 
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell($left_col_w, 9, ' 1. ENROLLMENT & COURSE INFORMATION', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(45, 10, ' Student Full Name', 1, 0); 
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell(95, 10, ' ' . strtoupper($student['name']), 1, 1);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(45, 10, ' Course Chosen', 1, 0); $pdf->Cell(95, 10, ' ' . $student['course'], 1, 1);
$pdf->Cell(45, 10, ' Unique Student ID', 1, 0); $pdf->Cell(95, 10, ' ' . $student['student_id'], 1, 1);
$pdf->Cell(45, 10, ' Registration No.', 1, 0); $pdf->Cell(95, 10, ' ' . ($student['nielit_registration_no'] ?: 'N/A'), 1, 1);
$pdf->Cell(45, 10, ' APAAR ID', 1, 0); $pdf->Cell(95, 10, ' ' . ($student['apaar_id'] ?: 'N/A'), 1, 1);
$pdf->Ln(4);

// Section 2: Personal Profile
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($left_col_w, 9, ' 2. CANDIDATE PERSONAL PROFILE', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 10);
$c1 = 30; $c2 = 40; 
$pdf->Cell($c1, 9, ' Father Name', 1, 0); $pdf->Cell($c2, 9, ' '.$student['father_name'], 1, 0);
$pdf->Cell($c1, 9, ' Mother Name', 1, 0); $pdf->Cell($c2, 9, ' '.$student['mother_name'], 1, 1);
$pdf->Cell($c1, 9, ' Date of Birth', 1, 0); $pdf->Cell($c2, 9, ' '.$student['dob'], 1, 0);
$pdf->Cell($c1, 9, ' Religion', 1, 0); $pdf->Cell($c2, 9, ' '.$student['religion'], 1, 1);
$pdf->Cell($c1, 9, ' Gender', 1, 0); $pdf->Cell($c2, 9, ' '.$student['gender'], 1, 0);
$pdf->Cell($c1, 9, ' Category', 1, 0); $pdf->Cell($c2, 9, ' '.$student['category'], 1, 1);
$pdf->Cell($c1, 9, ' Nationality', 1, 0); $pdf->Cell($c2, 9, ' '.$student['nationality'], 1, 0);
$pdf->Cell($c1, 9, ' Marital Status', 1, 0); $pdf->Cell($c2, 9, ' '.$student['marital_status'], 1, 1);
$pdf->Cell($c1, 9, ' Aadhar Number', 1, 0); $pdf->Cell($c2, 9, ' '.$student['aadhar'], 1, 0);
$pdf->Cell($c1, 9, ' PWD Status', 1, 0); $pdf->Cell($c2, 9, ' '.$student['pwd_status'], 1, 1);

// Distinguishing Mark Fix
$mark_text = ' ' . ($student['distinguishing_marks'] ?: 'None');
$mark_h = max(10, $pdf->getStringHeight(110, $mark_text));
$pdf->Cell($c1, $mark_h, ' Birth Mark', 1, 0, 'L'); 
$pdf->MultiCell(110, $mark_h, $mark_text, 1, 'L', false, 1);
$pdf->Ln(6);

// Section 3: Contact
$full_w = 180;
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 3. CONTACT & COMMUNICATION DETAILS', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(45, 11, ' Mobile Number', 1, 0); $pdf->Cell(45, 11, ' '.$student['mobile'], 1, 0);
$pdf->Cell(35, 11, ' Email ID', 1, 0); 
$pdf->MultiCell(55, 11, ' '.$student['email'], 1, 'L', false, 1);

$addr_text = $student['address'].", ".$student['city'].", ".$student['state']." - ".$student['pincode'];
$addr_h = max(12, $pdf->getStringHeight(135, $addr_text));
$pdf->Cell(45, $addr_h, ' Full Address', 1, 0);
$pdf->MultiCell(135, $addr_h, ' '.$addr_text, 1, 'L', false, 1);
$pdf->Ln(6);

// Section 4: Institutional
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 4. INSTITUTIONAL & ACADEMIC INFO', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(50, 11, ' Training Centre', 1, 0); $pdf->Cell(130, 11, ' '.($student['training_center'] ?: 'NIELIT BHUBANESWAR'), 1, 1);
$pdf->Cell(50, 11, ' Last College Name', 1, 0); $pdf->Cell(130, 11, ' '.$student['college_name'], 1, 1);
$pdf->Cell(50, 11, ' Fee Payment UTR', 1, 0); $pdf->Cell(130, 11, ' '.($student['utr_number'] ?: 'N/A'), 1, 1);

// --- 7. PAGE 2: EDUCATION & OFFICE VERIFICATION ---
$pdf->AddPage();
$pdf->Ln(5);

// Section 5: Education Table
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 5. ACADEMIC QUALIFICATION HISTORY', 0, 1, 'L', true);
$pdf->SetFont('helvetica', 'B', 10);
$pdf->SetFillColor(230, 240, 255);
$pdf->Cell(15, 12, 'Sl No', 1, 0, 'C', true); $pdf->Cell(30, 12, 'Examination', 1, 0, 'C', true); 
$pdf->Cell(60, 12, 'University / Board', 1, 0, 'C', true); $pdf->Cell(20, 12, 'Year', 1, 0, 'C', true); 
$pdf->Cell(30, 12, 'Stream', 1, 0, 'C', true); $pdf->Cell(25, 12, '% / CGPA', 1, 1, 'C', true);

$pdf->SetFont('helvetica', '', 10);
if (!empty($education_records)) {
    $i = 1;
    foreach ($education_records as $edu) {
        $pdf->Cell(15, 11, $i++, 1, 0, 'C');
        $pdf->Cell(30, 11, ' '.$edu['exam_passed'], 1, 0);
        $pdf->Cell(60, 11, ' '.$edu['institute_name'], 1, 0);
        $pdf->Cell(20, 11, $edu['year_of_passing'], 1, 0, 'C');
        $pdf->Cell(30, 11, ' '.$edu['stream'], 1, 0);
        $pdf->Cell(25, 11, $edu['percentage'], 1, 1, 'C');
    }
} else { $pdf->Cell($full_w, 12, 'No records found.', 1, 1, 'C'); }
$pdf->Ln(10);

// Section 6: Document Checklist
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 6. DOCUMENT SUBMISSION CHECKLIST', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 11);
$docs_checklist = [
    'Aadhar Card' => 'aadhar_card_doc', '10th Certificate' => 'tenth_marksheet_doc', 
    '12th/Diploma Cert' => 'twelfth_marksheet_doc', 'Graduation Certificate' => 'graduation_certificate_doc', 
    'Caste Certificate' => 'caste_certificate_doc', 'Payment Receipt' => 'payment_receipt'
];
$j = 0;
foreach ($docs_checklist as $label => $key) {
    $pdf->Cell(45, 11, ' '.$label, 1, 0);
    $pdf->Cell(45, 11, (!empty($student[$key]) ? '[ SUBMITTED ]' : '[ PENDING ]'), 1, ($j % 2 == 1 ? 1 : 0), 'C');
    $j++;
}
$pdf->Ln(10);

// Section 7: Office Use
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 7. FOR OFFICE USE ONLY', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(60, 13, ' Document Verification:', 1, 0); $pdf->Cell(120, 13, ' [   ] Verified    [   ] Under Review    [   ] Discrepancy Found', 1, 1);
$pdf->Cell(60, 15, ' Signature of Official/Nodal officer/Project incharge:', 1, 0); $pdf->Cell(120, 15, ' __________________________________________', 1, 1);

$pdf->Ln(15);
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell(0, 7, ' DECLARATION BY CANDIDATE', 0, 1, 'L');
$pdf->SetFont('freesans', '', 10);
$dec_text = "I hereby declare that the information provided above is true and correct to the best of my knowledge. I understand that any false information may result in the cancellation of my admission/registration.\n\nमैं एतद्द्वारा घोषणा करता/करती हूं कि ऊपर दी गई जानकारी मेरी जानकारी के अनुसार सत्य और सही है। मैं समझता/समझती हूं कि कोई भी गलत जानकारी मेरे प्रवेश/प्रंजीकरण को रद्द कर सकती है।";
$pdf->MultiCell($full_w, 8, $dec_text, 0, 'L');

$pdf->Ln(25);
$pdf->SetFont('freesans', 'B', 11);
$pdf->Cell(90, 5, 'Date: ________________', 0, 0);
$pdf->Cell(90, 5, 'Signature of Candidate', 0, 1, 'R');

$pdf_name = 'NIELIT_Admission_Form_' . $student['student_id'] . '.pdf';
$pdf->Output($pdf_name, 'D');

$conn->close();
?>