<?php
/**
 * Shared PDF renderer for student admission forms (one PDF per course enrollment).
 */
require_once __DIR__ . '/student_form_helpers.php';
require_once __DIR__ . '/tcpdf_devanagari_font.php';

if (!defined('INSTITUTE_NAME_EN')) {
    require_once __DIR__ . '/institute_branding.php';
}

if (!class_exists('NIELIT_PDF')) {
    require_once __DIR__ . '/../libraries/tcpdf/tcpdf.php';

    class NIELIT_PDF extends TCPDF {
    public function Header() {
        // Professional Page Border
        $this->SetDrawColor(100, 100, 100);
        $this->SetLineWidth(0.6);
        $this->Rect(10, 10, 190, 275, 'D');

        // --- ULTRA-LIGHT WATERMARK ---
        $this->SetFont('helvetica', 'B', 50);
        
        // Lightened from 200 to 235 (Closer to white)
        $this->SetDrawColor(235, 235, 235); 
        
        // Reduced opacity from 0.35 to 0.18 for a "ghost" effect
        $this->SetAlpha(0.18); 

        $this->StartTransform();
        $this->Rotate(45, 105, 148);
        $this->setTextRenderingMode(1, true, false); // Outline only
        $this->Text(20, 150, 'NIELIT BHUBANESWAR');
        $this->setTextRenderingMode(0, true, false); // Reset to Fill
        $this->StopTransform(); 
        
        // Reset everything for the main content
        $this->SetAlpha(1); 
        $this->SetDrawColor(0, 0, 0); 
    }   

    public function Footer() {
        $this->SetY(-10); 
        $this->SetFont('helvetica', 'I', 9);
        $this->SetTextColor(120, 120, 120);
        $this->Cell(0, 10, 'Generated by NIELIT Management System | Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, 0, 'C');
    }
}
}

if (!function_exists('smartTruncate')) {
function smartTruncate($text, $maxLength, $suffix = '...') {
    if (empty($text)) return '';
    
    $text = trim($text);
    if (strlen($text) <= $maxLength) return $text;
    
    // Try to break at word boundary
    $truncated = substr($text, 0, $maxLength - strlen($suffix));
    $lastSpace = strrpos($truncated, ' ');
    
    if ($lastSpace !== false && $lastSpace > $maxLength * 0.6) {
        $truncated = substr($truncated, 0, $lastSpace);
    }
    
    return $truncated . $suffix;
}
}

if (!function_exists('compactAddress')) {
function compactAddress($addressParts, $maxLength = 90) {
    $parts = array_filter(array_map('trim', $addressParts), function ($value) {
        return $value !== '' && strtolower($value) !== 'n/a';
    });

    if (empty($parts)) {
        return ' N/A';
    }

    return ' ' . implode("\n", $parts);
}
}

if (!function_exists('renderCompactAddressRow')) {
function renderCompactAddressRow($pdf, $labelWidth, $valueWidth, $addressParts) {
    $lines = array_values(array_filter(array_map('trim', $addressParts), function ($value) {
        return $value !== '' && strtolower($value) !== 'n/a';
    }));

    if (empty($lines)) {
        $lines = ['N/A'];
    }

    $leftLine = implode(', ', array_slice($lines, 0, 2));
    $rightLine = implode(', ', array_slice($lines, 2));
    if ($rightLine === '') {
        $rightLine = ' ';
    }

    $pdf->SetFont('helvetica', '', 8);
    $halfWidth = $valueWidth / 2;
    $rowHeight = max(
        12,
        $pdf->getStringHeight($halfWidth, ' ' . $leftLine),
        $pdf->getStringHeight($halfWidth, ' ' . $rightLine)
    );

    $pdf->Cell($labelWidth, $rowHeight, ' Full Address', 1, 0, 'L');
    $pdf->MultiCell($halfWidth, $rowHeight, ' ' . $leftLine, 1, 'L', false, 0);
    $pdf->MultiCell($halfWidth, $rowHeight, ' ' . $rightLine, 1, 'L', false, 1);
}
}

if (!function_exists('renderWrappedEducationRow')) {
function renderWrappedEducationRow($pdf, $widths, $serial, $exam, $institute, $year, $stream, $percentage) {
    $exam = ' ' . trim((string) $exam);
    $institute = ' ' . trim((string) $institute);
    $stream = ' ' . trim((string) $stream);

    $rowHeight = max(
        13,
        $pdf->getStringHeight($widths['exam'], $exam),
        $pdf->getStringHeight($widths['institute'], $institute),
        $pdf->getStringHeight($widths['stream'], $stream)
    );

    $startX = $pdf->GetX();
    $startY = $pdf->GetY();

    $pdf->Cell($widths['sl'], $rowHeight, $serial, 1, 0, 'C');
    $pdf->MultiCell($widths['exam'], $rowHeight, $exam, 1, 'L', false, 0, '', '', true, 0, false, true, $rowHeight, 'M');
    $pdf->MultiCell($widths['institute'], $rowHeight, $institute, 1, 'L', false, 0, '', '', true, 0, false, true, $rowHeight, 'M');
    $pdf->Cell($widths['year'], $rowHeight, ' ' . trim((string) $year), 1, 0, 'C');
    $pdf->MultiCell($widths['stream'], $rowHeight, $stream, 1, 'L', false, 0, '', '', true, 0, false, true, $rowHeight, 'M');
    $pdf->Cell($widths['percentage'], $rowHeight, ' ' . trim((string) $percentage), 1, 1, 'C');

    $pdf->SetXY($startX, $startY + $rowHeight);
}
}

function renderStudentAdmissionFormPdf(array $student, array $education_records, string $outputDest = 'D', ?string $outputPath = null): void {
    while (ob_get_level() > 0) {
        ob_end_clean();
    }

    $prevDisplayErrors = ini_get('display_errors');
    ini_set('display_errors', '0');

    $hindiFont = getTcpdfDevanagariFontName();
    $hindiTexts = getAdmissionFormHindiTexts();

$pdf = new NIELIT_PDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetMargins(15, 20, 15);
$pdf->SetAutoPageBreak(TRUE, 25);
$pdf->AddPage();

// --- 4. BRANDING HEADER (logo left, institute text beside it) ---
$logo_path = __DIR__ . '/../assets/images/bhubaneswar_logo.png';
$marginLeft = 15;
$marginRight = 15;
$headerY = 15;
$logoWidth = 24;
$logoGap = 5;
$contentRight = 210 - $marginRight;
$textX = $marginLeft;
$textWidth = $contentRight - $marginLeft;
$logoHeight = 0;

if (file_exists($logo_path)) {
    $imgSize = @getimagesize($logo_path);
    $logoHeight = ($imgSize && !empty($imgSize[0]))
        ? $logoWidth * ($imgSize[1] / $imgSize[0])
        : 22;
    $pdf->Image($logo_path, $marginLeft, $headerY, $logoWidth, 0, 'PNG');
    $textX = $marginLeft + $logoWidth + $logoGap;
    $textWidth = $contentRight - $textX;
}

$hindiLineHeight = 0;
if ($hindiFont) {
    $pdf->SetFont($hindiFont, '', 10);
    $hindiLineHeight = max(5, $pdf->getStringHeight($textWidth, $hindiTexts['institute_line']));
}
$pdf->SetFont('helvetica', 'B', 10);
$englishLineHeight = max(5, $pdf->getStringHeight($textWidth, INSTITUTE_NAME_EN));
$textBlockHeight = ($hindiFont ? $hindiLineHeight + 1 : 0) + $englishLineHeight;

$textY = $headerY;
if ($logoHeight > 0 && $logoHeight > $textBlockHeight) {
    $textY = $headerY + (($logoHeight - $textBlockHeight) / 2);
}

$pdf->SetXY($textX, $textY);
if ($hindiFont) {
    $pdf->SetFont($hindiFont, '', 10);
    $pdf->MultiCell($textWidth, 5, $hindiTexts['institute_line'], 0, 'C', false, 1, $textX, $textY);
}
$pdf->SetXY($textX, $pdf->GetY());
$pdf->SetFont('helvetica', 'B', 10);
$pdf->MultiCell($textWidth, 5, INSTITUTE_NAME_EN, 0, 'C', false, 1, $textX, $pdf->GetY());

$headerBottomY = max($pdf->GetY(), $headerY + $logoHeight);
$pdf->SetY($headerBottomY + 6);
$pdf->SetFont('helvetica', 'B', 16);
$pdf->SetTextColor(33, 150, 243);
$pdf->Cell(0, 12, 'ADMISSION APPLICATION FORM', 0, 1, 'C');
$pdf->SetTextColor(0, 0, 0);

$pdf->Ln(2);
$pdf->SetDrawColor(180, 180, 180);
$pdf->Line(15, $pdf->GetY(), 195, $pdf->GetY());
$pdf->Ln(6);

// --- 5. MEDIA ZONE (PHOTO & SIGNATURE) ---
$photo_x = 158; 
$start_y = $pdf->GetY();

$photo_path = !empty($student['passport_photo']) ? __DIR__ . '/../' . $student['passport_photo'] : '';
if (!empty($photo_path) && file_exists($photo_path)) {
    $pdf->Image($photo_path, $photo_x, $start_y, 37, 48, '', '', '', true, 300);
} else {
    $pdf->Rect($photo_x, $start_y, 37, 48, 'D');
}

$sig_y = $start_y + 54; 
$pdf->Rect($photo_x, $sig_y, 37, 18, 'D');
$sig_path = !empty($student['signature']) ? __DIR__ . '/../' . $student['signature'] : '';
if (!empty($sig_path) && file_exists($sig_path)) {
    $pdf->Image($sig_path, $photo_x + 1, $sig_y + 1, 35, 16, '', '', '', true, 300);
}
$pdf->SetXY($photo_x, $sig_y + 18);
$pdf->SetFont('helvetica', 'B', 8);
$pdf->Cell(37, 6, 'CANDIDATE SIGNATURE', 0, 0, 'C');

// --- 6. DATA TABLES ---
$pdf->SetY($start_y);
$left_col_w = 140; 

// Section 1: Enrollment
$pdf->SetFont('helvetica', 'B', 11); 
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell($left_col_w, 9, ' 1. ENROLLMENT & COURSE INFORMATION', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(45, 10, ' Student Full Name', 1, 0); 
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell(95, 10, ' ' . strtoupper($student['name']), 1, 1);
$pdf->SetFont('helvetica', '', 11);

// Course Chosen with proper text wrapping
$course_text = ' ' . $student['course'];
$course_height = max(10, $pdf->getStringHeight(95, $course_text));
$pdf->Cell(45, $course_height, ' Course Chosen', 1, 0, 'L'); 
$pdf->MultiCell(95, $course_height, $course_text, 1, 'L', false, 1);
$pdf->Cell(45, 10, ' Unique Student ID', 1, 0); $pdf->Cell(95, 10, ' ' . $student['student_id'], 1, 1);
$pdf->Cell(45, 10, ' Registration No.', 1, 0); $pdf->Cell(95, 10, ' ' . ($student['nielit_registration_no'] ?: 'N/A'), 1, 1);
$pdf->Cell(45, 10, ' APAAR ID', 1, 0); $pdf->Cell(95, 10, ' ' . ($student['apaar_id'] ?: 'N/A'), 1, 1);
$pdf->Ln(4);

// Section 2: Personal Profile
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($left_col_w, 9, ' 2. CANDIDATE PERSONAL PROFILE', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 10);
$c1 = 30; $c2 = 40; 

// Father Name - with text wrapping for long names
$father_text = ' '.smartTruncate($student['father_name'], 30);
$father_h = max(9, $pdf->getStringHeight(40, $father_text));
$pdf->Cell($c1, $father_h, ' Father Name', 1, 0, 'L'); 
$pdf->MultiCell($c2, $father_h, $father_text, 1, 'L', false, 0);
$pdf->Cell($c1, $father_h, ' Mother Name', 1, 0); 
$pdf->MultiCell($c2, $father_h, ' '.smartTruncate($student['mother_name'], 30), 1, 'L', false, 1);

$pdf->Cell($c1, 9, ' Date of Birth', 1, 0); $pdf->Cell($c2, 9, ' '.$student['dob'], 1, 0);
$pdf->Cell($c1, 9, ' Religion', 1, 0); $pdf->Cell($c2, 9, ' '.$student['religion'], 1, 1);
$pdf->Cell($c1, 9, ' Gender', 1, 0); $pdf->Cell($c2, 9, ' '.$student['gender'], 1, 0);
$pdf->Cell($c1, 9, ' Category', 1, 0); $pdf->Cell($c2, 9, ' '.$student['category'], 1, 1);
$pdf->Cell($c1, 9, ' Nationality', 1, 0); $pdf->Cell($c2, 9, ' '.$student['nationality'], 1, 0);
$pdf->Cell($c1, 9, ' Marital Status', 1, 0); $pdf->Cell($c2, 9, ' '.$student['marital_status'], 1, 1);
$pdf->Cell($c1, 9, ' Aadhar Number', 1, 0); $pdf->Cell($c2, 9, ' '.$student['aadhar'], 1, 0);
$pdf->Cell($c1, 9, ' PWD Status', 1, 0); $pdf->Cell($c2, 9, ' '.$student['pwd_status'], 1, 1);

// Distinguishing Mark Fix
$mark_text = ' ' . ($student['distinguishing_marks'] ?: 'None');
$mark_h = max(10, $pdf->getStringHeight(110, $mark_text));
$pdf->Cell($c1, $mark_h, ' Birth Mark', 1, 0, 'L'); 
$pdf->MultiCell(110, $mark_h, $mark_text, 1, 'L', false, 1);
$pdf->Ln(6);

// Section 3: Contact
$full_w = 180;
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 3. CONTACT & COMMUNICATION DETAILS', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(45, 9, ' Mobile Number', 1, 0); $pdf->Cell(45, 9, ' '.$student['mobile'], 1, 0);
$pdf->Cell(35, 9, ' Email ID', 1, 0); 
$pdf->MultiCell(55, 9, ' '.$student['email'], 1, 'L', false, 1);

$addr_text = compactAddress([
    $student['address'] ?? '',
    $student['city'] ?? '',
    $student['state'] ?? '',
    !empty($student['pincode']) ? 'PIN ' . $student['pincode'] : ''
], 85);
$pdf->SetFont('helvetica', '', 10);
renderCompactAddressRow($pdf, 45, 135, [
    $student['address'] ?? '',
    $student['city'] ?? '',
    $student['state'] ?? '',
    !empty($student['pincode']) ? 'PIN ' . $student['pincode'] : ''
]);
$pdf->Ln(4);

// Section 4: Institutional
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 4. INSTITUTIONAL & ACADEMIC INFO', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 11);

// Training Centre with text wrapping
$training_center_text = ' '.($student['training_center'] ?: 'NIELIT Bhubaneswar|Baleshwar|Raipur');
$training_center_height = max(9, $pdf->getStringHeight(130, $training_center_text));
$pdf->Cell(50, $training_center_height, ' Training Centre', 1, 0); 
$pdf->MultiCell(130, $training_center_height, $training_center_text, 1, 'L', false, 1);

// Last College Name with text wrapping
$college_name_text = ' '.$student['college_name'];
$college_name_height = max(9, $pdf->getStringHeight(130, $college_name_text));
$pdf->Cell(50, $college_name_height, ' Last College Name', 1, 0); 
$pdf->MultiCell(130, $college_name_height, $college_name_text, 1, 'L', false, 1);
$pdf->Cell(50, 9, ' Fee Payment UTR', 1, 0); $pdf->Cell(130, 9, ' '.($student['utr_number'] ?: 'N/A'), 1, 1);

// --- 7. PAGE 2: EDUCATION & OFFICE VERIFICATION ---
$pdf->AddPage();
$pdf->Ln(5);

// Section 5: Education Table
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 5. ACADEMIC QUALIFICATION HISTORY', 0, 1, 'L', true);

// Enhanced table with better column widths and text wrapping
$pdf->SetFont('helvetica', 'B', 9);
$pdf->SetFillColor(230, 240, 255);

// Optimized column widths for better text fitting
$col_widths = [
    'sl' => 12,      // Serial number - reduced
    'exam' => 35,    // Examination - increased
    'institute' => 55, // University/Board - reduced slightly
    'year' => 18,    // Year - increased slightly
    'stream' => 32,  // Stream - increased
    'percentage' => 28 // Percentage - increased
];

// Table headers with proper alignment
$pdf->Cell($col_widths['sl'], 12, 'Sl No', 1, 0, 'C', true);
$pdf->Cell($col_widths['exam'], 12, 'Examination', 1, 0, 'C', true);
$pdf->Cell($col_widths['institute'], 12, 'University / Board', 1, 0, 'C', true);
$pdf->Cell($col_widths['year'], 12, 'Year', 1, 0, 'C', true);
$pdf->Cell($col_widths['stream'], 12, 'Stream', 1, 0, 'C', true);
$pdf->Cell($col_widths['percentage'], 12, '% / CGPA', 1, 1, 'C', true);

$pdf->SetFont('helvetica', '', 8); // Reduced font size for better fitting

if (!empty($education_records)) {
    $i = 1;
    foreach ($education_records as $edu) {
        renderWrappedEducationRow(
            $pdf,
            $col_widths,
            $i++,
            $edu['exam_passed'] ?? '',
            $edu['institute_name'] ?? '',
            $edu['year_of_passing'] ?? '',
            $edu['stream'] ?? '',
            $edu['percentage'] ?? ''
        );
    }
} else { 
    $pdf->Cell($full_w, 14, 'No education records found.', 1, 1, 'C'); 
}

$pdf->Ln(4);

// Section 6: Document Checklist
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 6. DOCUMENT SUBMISSION CHECKLIST', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 11);
$docs_checklist = [
    'Aadhar Card' => 'aadhar_card_doc', '10th Certificate' => 'tenth_marksheet_doc', 
    '12th/Diploma Cert' => 'twelfth_marksheet_doc', 'Graduation Certificate' => 'graduation_certificate_doc', 
    'Caste Certificate' => 'caste_certificate_doc', 'Payment Receipt' => 'payment_receipt'
];
$j = 0;
foreach ($docs_checklist as $label => $key) {
    $pdf->Cell(45, 9, ' '.$label, 1, 0);
    $pdf->Cell(45, 9, (!empty($student[$key]) ? '[ SUBMITTED ]' : '[ PENDING ]'), 1, ($j % 2 == 1 ? 1 : 0), 'C');
    $j++;
}
$pdf->Ln(4);

// Section 7: Office Use
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell($full_w, 9, ' 7. FOR OFFICE USE ONLY', 0, 1, 'L', true);
$pdf->SetFont('helvetica', '', 10);
$label1 = ' Document Verification:';
$opts = ' [   ] Verified    [   ] Under Review    [   ] Discrepancy Found';
$h1 = max(10, $pdf->getStringHeight(120, $opts));
$pdf->Cell(60, $h1, $label1, 1, 0);
$pdf->MultiCell(120, $h1, $opts, 1, 'L', false, 1);

$label2 = ' Signature of Official/Nodal Officer/Project Incharge:';
$sigText = '';
$dateText = ' Date: ___________';
$label2_h = max(11, $pdf->getStringHeight(60, $label2));
$rowH = max($label2_h, 11);
$pdf->MultiCell(60, $rowH, $label2, 1, 'L', false, 0);
$pdf->Cell(80, $rowH, $sigText, 1, 0);
$pdf->Cell(40, $rowH, $dateText, 1, 1);

$pdf->Ln(6);
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell(0, 7, ' DECLARATION BY CANDIDATE', 0, 1, 'L');
$pdf->SetFont('helvetica', '', 9);
$dec_english = "I hereby declare that the information provided above is true and correct to the best of my knowledge. I understand that any false information may result in the cancellation of my admission/registration.";
$pdf->MultiCell($full_w, 6, $dec_english, 0, 'L');
if ($hindiFont) {
    $pdf->Ln(2);
    $pdf->SetFont($hindiFont, '', 9);
    $pdf->MultiCell($full_w, 6, $hindiTexts['declaration'], 0, 'L');
}

$thumb_box_w = 34;
$thumb_box_h = 16;
$thumb_x = 15 + (($full_w - $thumb_box_w) / 2);
$thumb_y = $pdf->GetY() + 2;
$thumb_path = !empty($student['left_thumb_impression']) ? __DIR__ . '/../' . $student['left_thumb_impression'] : '';
$pdf->Rect($thumb_x, $thumb_y, $thumb_box_w, $thumb_box_h, 'D');
if (!empty($thumb_path) && file_exists($thumb_path)) {
    $thumb_ext = strtolower(pathinfo($thumb_path, PATHINFO_EXTENSION));
    if (in_array($thumb_ext, ['jpg', 'jpeg', 'png'])) {
        $pdf->Image($thumb_path, $thumb_x + 1, $thumb_y + 1, $thumb_box_w - 2, $thumb_box_h - 2, '', '', '', true, 300);
    }
}
$pdf->SetXY($thumb_x, $thumb_y + $thumb_box_h + 1);
$pdf->SetFont('helvetica', 'B', 8);
$pdf->Cell($thumb_box_w, 3, 'LEFT HAND THUMB IMPRESSION', 0, 1, 'C');
$pdf->Ln(1);

$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell(90, 5, 'Date: ________________', 0, 0);
$pdf->Cell(90, 5, 'Signature of Candidate', 0, 1, 'R');

$pdf_name = buildAdmissionFormFilename($student);
$pdf->Output($outputPath ?? $pdf_name, $outputDest);
    ini_set('display_errors', $prevDisplayErrors);
    exit;
}
